---
dependency:
  name: galaxy
  options:
    ignore-errors: true
driver:
  name: podman
platforms:
  - name: ubuntu-22.04
    image: docker.io/nmusatti/ubuntu2204-pys:latest
    pre_build_image: true
  - name: ubuntu-24.04
    image: docker.io/nmusatti/ubuntu2404-pys:latest
    pre_build_image: true
  - name: rockylinux8
    image: docker.io/nmusatti/rockylinux8-pys:latest
    pre_build_image: true
  - name: rockylinux9
    image: docker.io/nmusatti/rockylinux9-pys:latest
    pre_build_image: true

