name: GitHub Actions Molecule
run-name: Molecule 🚀
on: [push]
jobs:
  molecule_role_core_setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update && sudo apt install python3 python3-pip python3-venv
      - run: python3 -m venv ansible-molecule
      - run: source ansible-molecule/bin/activate && cd ansible-molecule && python3-pip install molecule 'molecule-plugins[podman]'
      
