name: GitHub Actions Molecule
run-name: Molecule 🚀
on: [push]
jobs:
  molecule_test:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update && sudo apt install python3 python3-pip
      - run: pwd && ls -rtl
